include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_single_quotes
    - unnecessary_statements
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_redundant_argument_values
    - avoid_void_async
    - eol_at_end_of_file
    - no_literal_bool_comparisons
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_null_aware_method_calls
    - unnecessary_parenthesis
    - use_super_parameters
    - unnecessary_breaks

analyzer:
  plugins:
    - custom_lint
